feat: add geoip and add header sample codes
aziontech/azion-samples pull request #4
Opened 2023-02-24 14:39 UTC by gabriel-azion

2023-02-24 16:01 UTC, paulopilottiduarte approved these changes

2023-02-24 20:11 UTC, MarianaAguilera approved these changes

2023-03-02 11:39 UTC, PabloDiehl requested changes
Just some stylish issues. 😬

2023-03-02 11:39 UTC, PabloDiehl commented on samples/edge-functions-firewall/geo-ip/add-response-header.js
> +    if (countryCode ==="BR"){
```suggestion
    if (countryCode === "BR"){
```

2023-03-02 11:39 UTC, PabloDiehl commented on samples/edge-functions-firewall/geo-ip/geo-ip-deny-country.js
> +    if (countryCode ==="BR"){
```suggestion
    if (countryCode === "BR"){
```

2023-03-02 11:59 UTC, PabloDiehl approved these changes

2023-03-02 11:59 UTC, merged